#!/bin/bash
### The next line is for DEBUGING purposes
#GITHUB_REPOSITORY="zentoshop/ext-m2-innoship"
ls -al
if [ ! -f composer.json ];
then
  echo "Error! composer.json File not found!"
  exit 1
fi

MODULE_VERSION=${GITHUB_REF##*/}
if [ "$MODULE_VERSION" == "dev" ]
then
  MODULE_VERSION="0.0.0.0"
fi
COMPOSER=$(jq ".version = \"$MODULE_VERSION\"" composer.json)
echo $COMPOSER | jq . > composer.json
cat composer.json
zip -r latest.zip * -x ".*"
aws s3 cp latest.zip s3://zento-modules/${GITHUB_REPOSITORY##*/}/${MODULE_VERSION}.zip
aws s3 cp composer.json s3://zento-modules/${GITHUB_REPOSITORY##*/}/${MODULE_VERSION}.json

REPO_NAME="${GITHUB_REPOSITORY##*/}"
TAGS=$(aws s3 ls s3://zento-modules/$REPO_NAME/ | grep json | grep -v "packages.json" | awk '{print $4}' | rev | cut -d"." -f2- | rev)
COUNT_TAGS="${#TAGS[@]}"
echo "$REPO_NAME has $COUNT_TAGS Available Tags: $TAGS"
if [[ "$COUNT_TAGS" > "0" ]]
then
  for TAG in $TAGS; do
    echo $TAG
    if [ "$TAG" == "dev" ]
    then
      # rewrite variable for future use
      TAG="0.0.0.0"
      TAGS=${TAGS/dev/0.0.0.0}
      aws s3 mv s3://zento-modules/$REPO_NAME/dev.zip s3://zento-modules/$REPO_NAME/$TAG.zip
      aws s3 mv s3://zento-modules/$REPO_NAME/dev.json s3://zento-modules/$REPO_NAME/$TAG.json
    fi
    aws s3 cp s3://zento-modules/$REPO_NAME/$TAG.json .
    if [ "$TAG" != "$(echo $TAGS | awk '{ print $NF }')" ];
    then
      NEXT=","
    else
      NEXT=""
    fi
    ### the next variables are used in templates/*.json
    COMPANY_NAME="$(jq .name $TAG.json | cut -d"/" -f1 | tr -d "\"")" 
    AUTOLOAD="$(jq .autoload $TAG.json)"
    REQUIRE="$(jq .require $TAG.json)"
    if [ "$TAG" = "$(echo $TAGS | awk '{ print $1 }')" ];
    then
      echo "Generating Header of packages.json ..."
      eval "cat <<EOF
      $(</tmp/packazento/templates/header.json)" > out.json
      cat out.json
    fi
    echo "Adding version $TAG to packages.json ..."
    eval "cat <<EOF
    $(</tmp/packazento/templates/version.json)" >> out.json
    cat out.json
  done
  echo "Adding footer to packages.json ..."
  echo "}}}" >> out.json # FOOTER
  echo "Check and set identation on packages.json ..."
  cat out.json
  echo "---"
  jq . out.json > packages.json
  cat packages.json
  aws s3 cp packages.json s3://zento-modules/$REPO_NAME/
fi
